### ISSUE TITLE
auth.getUser returns an error: Auth Session Missing v2.43.2

### ISSUE THREAD

**Issue by NickG-NZ** [supabase/auth-js#948]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
After upgrading from v2.38.4 to v2.43.2, calling auth.getUser in a NextJS route handler returns an` AuthSessionMissing` error for a logged in user (session cookie exists and is passed to the client).
It seems to be the same bug from issue supabase/supabase-js#1025  that was discovered and already fixed for edge functions. In this case it is happening when using the Supabase SSR library.

## To Reproduce

Steps to reproduce the behaviour, please provide code snippets or a repository:

Run `await supabaseAuthClient.auth.getUser() `in a NextJS route-handler (or presumably any serverless runtime using a supabase SSR client)

## Expected behavior
The user is returned.

## System information

- OS: Ubuntu 22
- Browser Chromium
- Version of supabase-js: 2.43.2
- Version of Node.js: 20

**Comment by tomasmenezes** [comment]
Just started getting this error on the latest `"@supabase/supabase-js": "^2.45.3"`. Rolling back to `2.45.1` seems to prevent it.

**Comment by Roni750** [comment]
> Hey everyone. Getting no user if the cookies are present means that you probably have an incorrect `middleware.ts` file. The middleware **must run.** If it doesn't the token will be refreshed multiple times causing _the following refresh_ to fail.
> 
> Please follow the SSR guides _to the dot._ https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=server-component&queryGroups=framework&framework=nextjs

You are definitely right about the middleware causing this issue (at least in my case). My middleware was just fine until I implemented protectedRoutes. It seems that the two asynchronous calls (one to updateSession from supabase/middleware, the other from my isAuthenticated custom function) caused this issue. Thank you for pointing that out, you're my saviour!

**Comment by sbhatm1213** [comment]
Facing this error still `AuthSessionMissingError: Auth session missing!` at http://localhost:3000/static/js/bundle.js:79331:20

Steps followed -
(1) Add Client ID and Secret on Supabase Google Auth Provider - Done
(2) Add Javascript origin - Done - http://localhost:3000/
(3) Add Redirect URI - Done - http://localhost:3000/auth/v1/callback and https://my-domain.supabase.co/auth/v1/callback
(4) Add code for `onAuthStateChange` - Done
(5) Try using `const { data: { session } } = await supabase.auth.getSession()`  - Done - Doesn't work
(6) Try using `const { data: { user } } = await supabase.auth.getUser()` - Done - Doesn't work 
(7) Try with different `gotrue-js` version - Done - "@supabase/supabase-js": {
      "@supabase/gotrue-js": "2.43.1"
    }
(8) Try on Firefox - Done - This works fine , so on Chrome is the problem

Same issue even with Azure

Although login happens, cannot get the session/user

**Comment by e-Naeim** [comment]
I'm getting same issue

**Comment by awseeley** [comment]
Hi all - i am facing the same issue. Tried suggestions in this thread to go back to an older version of `supabase/supabase-js` and `@supabase/ssr` with no luck.

"next": "^14.2.13",
"@supabase/ssr": "^0.5.1",
"@supabase/supabase-js": "^2.46.1",


My supabase middleware looks like the following, I have added some console logs to troubleshoot. I can see the `getAll` logs out the supabase auth token (sb-xxx-auth). 

However `await supabase.auth.getUser();` still has authsession missing.
{ user: null }
 [AuthSessionMissingError: Auth session missing!] {
  __isAuthError: true,
  name: 'AuthSessionMissingError',
  status: 400,
  code: undefined
}

```
export async function updateSession(request: NextRequest) {
  console.log("Update session middleware");
  let supabaseResponse = NextResponse.next({
    request,
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          console.log("get all cookies");
          const cookies = request.cookies.getAll();
          console.log(cookies);
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          console.log("Set all");
          console.log(cookiesToSet);
          cookiesToSet.forEach(({ name, value }) => {
            console.log("Set cookie ", name, value);
            request.cookies.set(name, value);
          });
          supabaseResponse = NextResponse.next({
            request,
          });
          cookiesToSet.forEach(({ name, value, options }) => {
            console.log("supabase cookied set ", name, value, options);
            supabaseResponse.cookies.set(name, value, options);
          });
        },
      },
    }
  );

  // refreshing the auth token
  const { data, error } = await supabase.auth.getUser();
  console.log("Middleware user");
  console.log(data);
  console.log(error);

  return supabaseResponse;
}
```

**Comment by k2xl** [comment]
Adding a solution I found for my particular instance in case it helps.

I was returning a singleton for createClient() calls from my backend (since I was getting 
`Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.` when running my jest tests. However, this was causing issues this auth session issue to happen to me (though strangely enough it didn't happen every time).

Anyway, getting rid of the singleton for createClient ended up resolving this for me

**Comment by harrisrobin** [comment]
I was facing this same issue, in my case it was because of a regression introduced in @supabase/auth-js:
https://github.com/supabase/auth-js/issues/995

**Comment by matart15** [comment]
Not sure it is a solution

On my edge function this was failing

```ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.36.0";
// Create a Supabase client with the Auth context of the logged in user.
const getSupabaseClient = (req: Request) => {
  console.log("qwerqwer", req.headers.get("Authorization"));
  const supabaseClient = createClient<Database>(
    // Supabase API URL - env var exported by default.
    Deno.env.get("SUPABASE_URL") ?? "",
    // Supabase API ANON KEY - env var exported by default.
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    // Create client with Auth context of the user that called the function.
    // This way your row-level-security (RLS) policies are applied.
    {
      global: {
        headers: { Authorization: req.headers.get("Authorization")! },
      },
    },
  );
  return supabaseClient;
};
```

and this succeeded
```ts
import {
  createClient,
  SupportedStorage,
} from "https://esm.sh/@supabase/supabase-js@2.46.1";
import { Database } from "./database.d.ts";

// Create a Supabase client with the Auth context of the logged in user.
const getSupabaseClient = (req: Request) => {
  console.log("qwerqwer", req.headers.get("Authorization"));
  const supabaseClient = createClient<Database>(
    // Supabase API URL - env var exported by default.
    Deno.env.get("SUPABASE_URL") ?? "",
    // Supabase API ANON KEY - env var exported by default.
    Deno.env.get("SUPABASE_ANON_KEY") ?? "",
    // Create client with Auth context of the user that called the function.
    // This way your row-level-security (RLS) policies are applied.
    {
      auth: { storage: inMemoryStorageProvider() },
      global: req
        ? {
            headers: { Authorization: req.headers.get("Authorization")! },
          }
        : undefined,
    },
  );
  return supabaseClient;
};

function inMemoryStorageProvider(): SupportedStorage {
  const items = new Map();
  return {
    getItem: (key: string) => items.get(key),
    setItem: (key: string, value: string) => {
      items.set(key, value);
    },
    removeItem: (key: string) => {
      items.delete(key);
    },
  } as SupportedStorage;
}
```


1. updated `@supabase/supabase-js@2.36.0` to `@supabase/supabase-js@2.46.1`
2. added `inMemoryStorageProvider`
